export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT'
export const FETCH_APPOINTMENT_COUNT = 'FETCH_APPOINTMENT_COUNT'
export const FETCH_APPOINTMENT_LIST = 'FETCH_APPOINTMENT_LIST'
export const FETCH_SINGLE_APPOINTMENT = 'FETCH_SINGLE_APPOINTMENT'
export const SET_LOAD_APPOINTMENT = 'SET_LOAD_APPOINTMENT'
export const SET_APPOINTMENT_DATE = 'SET_APPOINTMENT_DATE'
export const FETCH_REPARATION_LIST = 'FETCH_REPARATION_LIST'
export const MANUAL_APPOINTMENT_STATUS = 'MANUAL_APPOINTMENT_STATUS'

export default {
  CREATE_APPOINTMENT,
}
